title: Kevin Leander
email: ""
description: "Research and writing in literacy, technology, and education"
baseurl: ""
url: ""
theme: just-the-docs
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Just the Docs configuration
aux_links:
  "About": "/about/"

permalink: /:path/
